AventWithMVC/Models/Timesheet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AventWithMVC.Models
{
    public class Timesheet
    {
        public string time { get; set; }
        public DateTime startdate { get; set; }
        public DateTime enddate { get; set; }
    }
}

AventWithMVC/Models/Weeks.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AventWithMVC.Models
{
    public class Weeks
    {
        public int FirstWeek { get; set; }
        public int SecondWeek { get; set; }
        public int ThirdWeek { get; set; }
        public int FourthWeek { get; set; }
        public string month { get; set; }
        public int year { get; set; }
        public List<string> dates { get; set; }
        public List<int> WeekWiseHours { get; set; }
        public string WeekDates { get; set; }
        public string Startdate{ get; set; }
        public string Enddate { get; set; }
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Please enter numbers only")]
        public double Hours { get; set; }
        public double Avg { get; set; }
        public int Totalhours { get; set; }
        public int Numofleaves { get; set; }
    }
}

AventWithMVC/Controllers/TimesheetController.cs
using MySql.Data.MySqlClient;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AventWithMVC.Models;
using System.Configuration;

namespace AventWithMVC.Controllers
{
    public class TimesheetController : Controller
    {
        ArrayList dates = new ArrayList();
        ArrayList Tasks = new ArrayList();
        ArrayList Workinghours = new ArrayList();
        ArrayList finaldata = new ArrayList();
        string[] hr;

        MySql.Data.MySqlClient.MySqlConnection conn;
        string myConnectionString = ConfigurationManager.ConnectionStrings["MySQL"].ConnectionString;

        public ActionResult Timesheet()
        {
            DataSet ds = new DataSet();
            conn = new MySql.Data.MySqlClient.MySqlConnection(myConnectionString);
            string query = "sp_gettasks";
            MySqlCommand cmd = new MySqlCommand(query, conn);
            cmd.Connection = conn;
            cmd.CommandType = CommandType.StoredProcedure;
            using (MySqlDataAdapter sda = new MySqlDataAdapter(cmd))
            {
                sda.Fill(ds);
            }
            List<Dropdown> Objlistfortasktype = new List<Dropdown>();
            for (int y = 0; y < ds.Tables[0].Rows.Count; y++)
            {
                Dropdown Objddl = new Dropdown();
                Objddl.ddlvalue = Convert.ToInt32(ds.Tables[0].Rows[y]["Taskid"]);
                Objddl.ddltext = Convert.ToString(ds.Tables[0].Rows[y]["Taskname"]);
                Objlistfortasktype.Add(Objddl);
                ViewBag.Tasks = Objlistfortasktype;
            }

            return View();
        }

        [HttpPost]
        public JsonResult Timesheet(List<string> hours)
        {

            DataTable dt = new DataTable();
            dt.Columns.Add("Dates", typeof(string));
            dt.Columns.Add("Tasks", typeof(string));
            dt.Columns.Add("Hours", typeof(string));
            string[] ddlcount = hours[0].Split(',');
            for (int i = 1; i < hours.Count; i++)
            {
                string[] coltotal = hours[i].Split('!');
                string[] date = coltotal[0].Split('&');
                dates.Add(date[0]);
                hr = date[1].Split(',');
                for (int y = 0; y < hr.Count(); y++)
                {
                    Workinghours.Add(hr[y]);
                }
            }
            for (int j = 0; j < ddlcount.Count(); j++)
            {
                Tasks.Add(ddlcount[j]);
            }
            for (int x = 0; x < Tasks.Count; x++)
            {
                int p = x;
                DataRow[] sheetrow;
                for (int k = 0; k < dates.Count; k++)
                {
                    dt.Rows.Add(dates[k], Tasks[x]);
                    sheetrow = dt.Select("Dates='" + dates[k] + "' and Tasks='" + Tasks[x] + "'");
                    sheetrow[0]["Hours"] = Workinghours[p];
                    p = p + Tasks.Count;
                }
            }
            int o = dt.Rows.Count;

            for (int t = 0; t < dt.Rows.Count; t++)
            {
                conn = new MySql.Data.MySqlClient.MySqlConnection(myConnectionString);
                if (!string.IsNullOrEmpty(Convert.ToString(dt.Rows[t]["Dates"]))
                    && !string.IsNullOrEmpty(Convert.ToString(dt.Rows[t]["Tasks"]))
                    && !string.IsNullOrEmpty(Convert.ToString(dt.Rows[t]["Hours"])))
                {
                    string date = Convert.ToString(dt.Rows[t]["Dates"]);
                    int task = Convert.ToInt32(dt.Rows[t]["Tasks"]);
                    int hour = Convert.ToInt32(dt.Rows[t]["Hours"]);
                    conn.Open();
                    string query = "sp_instimesheet";
                    MySqlCommand cmd = new MySqlCommand(query, conn);
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@p_task", task);
                    cmd.Parameters.AddWithValue("@p_date", date);
                    try
                    {
                        if (!string.IsNullOrEmpty(Convert.ToString(dt.Rows[t]["Hours"])))
                        {
                            cmd.Parameters.AddWithValue("@p_hour", hour);
                        }
                        else
                        {
                            cmd.Parameters.AddWithValue("@p_hour", 0);
                        }
                        cmd.Connection = conn;
                        cmd.CommandType = CommandType.StoredProcedure;
                        int u = cmd.ExecuteNonQuery();
                        conn.Close();
                    }
                    catch (Exception ex)
                    {

                    }

                }


            }
            return Json("window.alert('HELLO');");
            //return JavaScript("window.alert('HELLO');");
            //return RedirectToAction("Timesheet");
        }
    }
}

AventWithMVC/Controllers/WeeksController.cs
using AventWithMVC.Models;
using MySql.Data.MySqlClient;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AventWithMVC.Controllers
{
    public class WeeksController : Controller
    {
        MySql.Data.MySqlClient.MySqlConnection conn;
        string myConnectionString = ConfigurationManager.ConnectionStrings["MySQL"].ConnectionString;

        ArrayList Startdate = new ArrayList();
        ArrayList Enddate = new ArrayList();
        ArrayList Hours = new ArrayList();
        ArrayList ArrNumberofleave = new ArrayList();
        // GET: Weeks
        List<Weeks> ObjweeksList = new List<Weeks>();

        //string EmpCode = Convert.ToString(Session["Emp_Code"]);
        //string EmpCode = "avent_005";
        int Currentmonth = DateTime.Now.Month;
        public ActionResult TimeSheetDashBoard()
        {
            return View();
        }


        [HttpGet]
        public ActionResult IndexMethod()
        {
            if (Session["Roleid"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }

        public ActionResult Index()
        {
            //List<string> weeks = new List<string>();
            DataSet dsWeeklySubmitted = new DataSet();
            dsWeeklySubmitted = GetWeeklyTimesIfExisted();
            if (!string.IsNullOrEmpty(Convert.ToString(dsWeeklySubmitted.Tables[2].Rows[0]["till_date_avg"])))
            {
                ViewBag.tilldateaverage = Convert.ToInt32(dsWeeklySubmitted.Tables[2].Rows[0]["till_date_avg"]);
            }
            if (!string.IsNullOrEmpty(Convert.ToString(dsWeeklySubmitted.Tables[2].Rows[0]["Empcode"])))
            {
                ViewBag.Empcode = Convert.ToString(dsWeeklySubmitted.Tables[2].Rows[0]["Empcode"]);
            }
            if (dsWeeklySubmitted.Tables[0] != null && dsWeeklySubmitted.Tables[0].Rows.Count > 0)
            {
                ViewBag.Totalhours = Convert.ToDouble(dsWeeklySubmitted.Tables[1].Rows[0]["Totalhours"]);
                for (int x = 0; x <= dsWeeklySubmitted.Tables[0].Rows.Count - 1 && x <= dsWeeklySubmitted.Tables[0].Rows.Count; x++)
                {
                    Weeks ObjExistingDates = new Weeks();
                    ObjExistingDates.Startdate = Convert.ToString(dsWeeklySubmitted.Tables[0].Rows[x]["StartDate"]);
                    ObjExistingDates.Enddate = Convert.ToString(dsWeeklySubmitted.Tables[0].Rows[x]["EndDate"]);
                    ObjExistingDates.Hours = Convert.ToDouble(dsWeeklySubmitted.Tables[0].Rows[x]["Hours"]);
                    ObjExistingDates.Avg = Convert.ToDouble(dsWeeklySubmitted.Tables[0].Rows[x]["daily_avg"]);
                    ObjExistingDates.Numofleaves = Convert.ToInt32(dsWeeklySubmitted.Tables[0].Rows[x]["number_of_leaves"]);
                    ObjweeksList.Add(ObjExistingDates);
                }
            }
            else
            {
                List<string> weekdays = GetDatesOnWeekWise(DateTime.Now.Year, DateTime.Now.Month).ToList();
                for (int i = 0; i < weekdays.Count; i++)
                {
                    Weeks ObjWeeks = new Weeks();
                    ObjWeeks.WeekDates = weekdays[i];
                    ObjweeksList.Add(ObjWeeks);
                }
            }
            ViewBag.Results = ObjweeksList;
            return View(ObjweeksList);
        }

        [HttpPost]
        public JsonResult Index(List<string> WeekWiseHoursandDates)
        {
            DataTable dt = new DataTable();
            dt.Columns.Add("StartDate", typeof(string));
            dt.Columns.Add("EndDate", typeof(string));
            //dt.Columns.Add("Hours", typeof(int));
            dt.Columns.Add("Hours", typeof(double));
            dt.Columns.Add("Numberofleave", typeof(int));

            for (int l = 0; l < WeekWiseHoursandDates.Count; l++)
            {
                string[] SplitingDatesandHours = WeekWiseHoursandDates[l].Split('&');
                string[] SplitingWeekdates = SplitingDatesandHours[0].Split('/');
                string[] Numbeofleave = SplitingDatesandHours[1].Split('#');
                Startdate.Add(SplitingWeekdates[0]);
                Enddate.Add(SplitingWeekdates[1]);
                Hours.Add(Numbeofleave[0]);
                ArrNumberofleave.Add(Numbeofleave[1]);
            }
            for (int p = 0; p < Startdate.Count; p++)
            {
                //if (!string.IsNullOrEmpty(Convert.ToString(Hours[p])))
                //if (Convert.ToDouble(Hours[p])>0 || !string.IsNullOrEmpty(Convert.ToString(Hours[p]))&& Convert.ToString(Hours[p])=="")
                if (Convert.ToString(Hours[p]) == "")
                {
                    Hours[p] = 0;
                    if (Convert.ToString(ArrNumberofleave[p]) == "")
                    {
                        ArrNumberofleave[p] = 0;
                        dt.Rows.Add(Startdate[p], Enddate[p], Hours[p], ArrNumberofleave[p]);
                    }
                    else
                    {
                        dt.Rows.Add(Startdate[p], Enddate[p], Hours[p], ArrNumberofleave[p]);
                    }
                }
                else
                {
                    if (Convert.ToString(ArrNumberofleave[p]) == "")
                    {
                        ArrNumberofleave[p] = 0;
                        dt.Rows.Add(Startdate[p], Enddate[p], Hours[p], ArrNumberofleave[p]);
                    }
                    else
                    {
                        dt.Rows.Add(Startdate[p], Enddate[p], Hours[p], ArrNumberofleave[p]);
                    }
                }
            }
            int u = InsertWeeklyTimes(dt);
            if (u > 0)
            {
                //string message = "Your details have been saved successfully.";
                //string script = "window.onload = function(){ alert('";
                //script += message;
                //script += "')};";
                //ClientScript.RegisterStartupScript(this.GetType(), "SuccessMessage", script, true);
                ViewData["Message"] = "Success";
            }
            //return Json("window.alert('HELLO');");
            //return RedirectToAction("Index", "Admin");
            return Json(new { }, JsonRequestBehavior.AllowGet);
        }

        //Testing Purpouse
        public ActionResult TimeSheetView()
        {
            dynamic mymodel = new ExpandoObject();
            mymodel.weeks = GetWeeklyTimesIfExisted();
            //List<string> weeks = new List<string>();
            DataSet dsWeeklySubmitted = new DataSet();
            dsWeeklySubmitted = GetWeeklyTimesIfExisted();
            if (!string.IsNullOrEmpty(Convert.ToString(dsWeeklySubmitted.Tables[2].Rows[0]["till_date_avg"])))
            {
                ViewBag.tilldateaverage = Convert.ToInt32(dsWeeklySubmitted.Tables[2].Rows[0]["till_date_avg"]);
            }
            if (!string.IsNullOrEmpty(Convert.ToString(dsWeeklySubmitted.Tables[2].Rows[0]["Empcode"])))
            {
                ViewBag.Empcode = Convert.ToString(dsWeeklySubmitted.Tables[2].Rows[0]["Empcode"]);
            }
            if (dsWeeklySubmitted.Tables[0] != null && dsWeeklySubmitted.Tables[0].Rows.Count > 0)
            {
                ViewBag.Totalhours = Convert.ToDouble(dsWeeklySubmitted.Tables[1].Rows[0]["Totalhours"]);
                for (int x = 0; x <= dsWeeklySubmitted.Tables[0].Rows.Count - 1 && x <= dsWeeklySubmitted.Tables[0].Rows.Count; x++)
                {
                    Weeks ObjExistingDates = new Weeks();
                    ObjExistingDates.Startdate = Convert.ToString(dsWeeklySubmitted.Tables[0].Rows[x]["StartDate"]);
                    ObjExistingDates.Enddate = Convert.ToString(dsWeeklySubmitted.Tables[0].Rows[x]["EndDate"]);
                    ObjExistingDates.Hours = Convert.ToDouble(dsWeeklySubmitted.Tables[0].Rows[x]["Hours"]);
                    ObjExistingDates.Avg = Convert.ToDouble(dsWeeklySubmitted.Tables[0].Rows[x]["daily_avg"]);
                    ObjExistingDates.Numofleaves = Convert.ToInt32(dsWeeklySubmitted.Tables[0].Rows[x]["number_of_leaves"]);
                    ObjweeksList.Add(ObjExistingDates);
                }
            }
            else
            {
                List<string> weekdays = GetDatesOnWeekWise(DateTime.Now.Year, DateTime.Now.Month).ToList();
                for (int i = 0; i < weekdays.Count; i++)
                {
                    Weeks ObjWeeks = new Weeks();
                    ObjWeeks.WeekDates = weekdays[i];
                    ObjweeksList.Add(ObjWeeks);
                }
            }
            ViewBag.Results = ObjweeksList;
            return View(ObjweeksList);
        }

        [HttpPost]
        public JsonResult TimeSheetView(List<string> WeekWiseHoursandDates)
        {
            DataTable dt = new DataTable();
            dt.Columns.Add("StartDate", typeof(string));
            dt.Columns.Add("EndDate", typeof(string));
            //dt.Columns.Add("Hours", typeof(int));
            dt.Columns.Add("Hours", typeof(double));
            dt.Columns.Add("Numberofleave", typeof(int));

            for (int l = 0; l < WeekWiseHoursandDates.Count; l++)
            {
                string[] SplitingDatesandHours = WeekWiseHoursandDates[l].Split('&');
                string[] SplitingWeekdates = SplitingDatesandHours[0].Split('/');
                string[] Numbeofleave = SplitingDatesandHours[1].Split('#');
                Startdate.Add(SplitingWeekdates[0]);
                Enddate.Add(SplitingWeekdates[1]);
                Hours.Add(Numbeofleave[0]);
                ArrNumberofleave.Add(Numbeofleave[1]);
            }
            for (int p = 0; p < Startdate.Count; p++)
            {

AventWithMVC/Views/Weeks/Index.cshtml
@model IEnumerable<AventWithMVC.Models.Weeks>

@{
    ViewBag.Title = "Weekly TimeSheet";
    Layout = "~/Views/Shared/_Adminlayout.cshtml";
}

<style>
    input {
        display: inline-block;
    }

    .sucess {
        color: forestgreen;
        text-align: right;
    }

    .items {
        overflow: hidden; /* simple clearfix */
    }

        .items .item {
            float: left;
            width: 85%;
        }

        .items .btnitem {
            width: 20%;
            padding-left: 15px;
        }
</style>


<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="jquery-3.3.1.min.js"></script>
</head>
<script>
    $(document).ready(function () {
        //$(".leaveclass").prop("disabled", true);
        const monthNames = ["January", "February", "March", "April", "May", "June",
                            "July", "August", "September", "October", "November", "December"
                            ];
        var date = new Date();
        document.getElementById("yearId").innerHTML = date.getFullYear();
        document.getElementById("monthId").innerHTML = monthNames[date.getMonth()]+"-";
        $(".hoursclass").on("keypress keyup blur", function (event) {
            if (this.value.length > 6) {
                return false;
            }
            //if ($('input:text').val()>50)
            //{
            //    event.preventDefault();
            //    //return false;
            //}
            
            $(this).val($(this).val().replace(/[^0-9\.]/g, ''));
            if ((event.which != 46 || $(this).val().indexOf('.') != -1) && (event.which < 48 || event.which > 57)) {
                event.preventDefault();
            }
            //else
            //{
            //    $(".leaveclass:selected").prop("disabled", false);
            //}
        });

        $('hoursclass').bootstrapValidator({
            container: '#messages',
            feedbackIcons: {
                invalid: '',
                validating: ''
            },
            fields: {
                txthr: {
                    selector: '.hoursclass',
                    validators: {
                        stringLength: {
                            min: 0,
                            max: 2,
                            message: 'The hours length not greater than two digits'
                        },
                        integer: {
                            message: 'The value is not an integer'
                        },
                        lessThan: {
                            value: 50,
                            //alert("The hours value not greater than 50");
                            message: 'The hours value not greater than 50'
                        }
                    }
                }
            }

        })

        $('#txt').bootstrapValidator({
            feedbackIcons: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                number: {
                    validators: {
                        integer: {
                            message: 'The value is not an integer'
                        }
                    }
                }
            }
        });
    });
    
    function showTableData()
    {
        var dates = [];
        var hours = [];
        var finaldata = [];
        var Days = []; var leaves = [];
        var strings;
        $('#tblbody tr').each(function () {
            var customerId = $(this).find(".customerIDCell").html();
            var Numberofleave = $(this).find(".leaveclass").val();
            customerId = customerId.replace("--","/");
            dates.push(customerId);
           leaves.push(Numberofleave);
            //alert("Date is:-" + datesandhours);
        });
        var sum = 0;
        $.each($('.hoursclass'), function () {
            var grade = $(this).val();
            sum += +grade
            //$(".myclass").val(sum);
            //$("#totalhrs").val(sum);
            document.getElementById("totalhrs").innerHTML = sum;
            hours.push(grade);
        });
     
        var trlenght = document.getElementById('tblbody').rows.length;
        var stng;
        var i;
        //var tdlength = document.getElementById('tblbody').rows[0].cells.length;
        for (i = 0; i < trlenght; i++)
        {
            finaldata.push(dates[i] + '&' + hours[i] + '#' + leaves[i]);
        }
        $.ajax({
            type: "POST",
            url: "@Url.Action("Index", "Weeks")",
            data: JSON.stringify(finaldata),
        dataType: "json",
        contentType: "application/json",
        success: function (data) {
            alert("Data Saved Succesfully");
            window.location.href = "/Weeks/Index";

        },
        failure: function (response)
        {
            alert(response.responseText);
        },
        dataType: "json",
        contentType: "application/json"
        });

    }
</script>

<style>
    .sucessmsg {
        color:green;
    }
    .footerfont {
       font-family: "Oswald", Helvetica, Arial, sans-serif!important;
    }
</style>

<body style="background-color:#F0EBD8">
    @using (Html.BeginForm("Index", "Weeks", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <div class="col-md-12 col-md-offset-3">
                <div id="messages"></div>
            </div>
        </div>
        <div style="padding-top:5%">
            <div id="popupdiv" style="border: 1px solid red; display: none;">
                @ViewData["Message"]
            </div>
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <div class="panel panel-default panel-table">
                        <div class="panel-heading" style="background-color:#0C2658">
                            <div class="row">
                                <div class="col col-xs-6">
                                    <h3 style="font-weight:bold;color: white" class="panel-title">Hours Tracking</h3>
                                </div>
                                <div class="col col-xs-4 text-right">
                                    <h3 id="monthId" style="font-weight:bold;padding-left:70%;color: white" class="panel-title col-xs-2"></h3>
                                    <h3 id="yearId" style="font-weight:bold;padding-left:30px;color: white" class="panel-title col-xs-2"></h3>
                                    @*<span id="yearId" style="font-size:100%;background-color:#733D8B" class="label label-info"></span>
                                        <span id="monthId" style="font-size:100%;background-color:#733D8B" class="label label-info"></span>*@
                                </div>
                            </div>
                        </div>

                        <div class="panel-body">
                            <table class="table table-striped table-bordered table-list" id="tblweekwise">
                                <thead>
                                    <tr class="row">
                                        <th class="col-md-5" width="5%">Weeks</th>
                                        <th class="col-md-3" width="5%">Hours</th>
                                        <th class="col-md-2" width="5%">Daily Average</th>
                                        <th class="col-md-2" width="5%">Number of leaves</th>
                                    </tr>
                                </thead>
                                <tbody id="tblbody">
                                    @foreach (var item in ViewBag.Results)
                                {
                                    if ((!string.IsNullOrEmpty(@item.Startdate)) && (!string.IsNullOrEmpty(@item.Enddate)))
                                    {
                                <tr class="row">
                                    <td align="center" id="dates" class="col-md-5">
                                        <em class="customerIDCell">@item.Startdate--@item.Enddate</em>
                                    </td>
                                    <td id="hours" class="col-md-3">
                                        <input id="txt" name="txthr" type="text" class="hoursclass" value="@item.Hours" />
                                    </td>
                                    @if (@item.Avg < 8.8)
                                            {
                                            <td class="col-md-2">
                                                <em class="" style="color:red;">@item.Avg</em>
                                            </td>
                                            }
                                            else
                                            {
                                            <td class="col-md-2">
                                                <em class="" style="color:green;">@item.Avg</em>
                                            </td>
                                            }
                                    <td class="col-md-2" style="text-align:center;">
                                        <input value="@item.Numofleaves" type="text" class="leaveclass" style="width:50%;" />
                                    </td>
                                </tr>
                                    }
                                    else
                                    {
                                <tr class="row">
                                    <td align="center" id="dates" class="col-md-5">
                                        <em class="customerIDCell">@item.WeekDates</em>
                                    </td>
                                    <td id="hours" class="col-md-3">
                                        <input id="txt" type="text" class="hoursclass" />
                                    </td>
                                    <td class="col-md-2">
                                        <label for="male"></label>
                                    </td>
                                    <td class="col-md-2" style="text-align:center;">
                                        <input value="" type="text" class="leaveclass" style="width:50%;" />
                                    </td>
                                </tr>
                                    }
                                }
                                </tbody>
                            </table>
                            <div class="row" style="font-size:18px;">
                                <div class="col-md-5" style="text-align:right;padding-left:15%">
                                    Total Hours:
                                </div>
                                <div class="col-md-2">
                                    <span id="totalhrs" style="font-size:100%;" class="myclass">@ViewBag.Totalhours</span>
                                </div>
                                <div class="col-md-3" style="text-align:right;">
                                    Average till date:
                                </div>
                                <div class="col-md-1" style="text-align:left;padding-left:0px;">
                                    @ViewBag.tilldateaverage
                                </div>
                            </div>
                            @*<div class="row">
                                    <div class="col col-md-7 pull-left total" style="font-size:18px;padding-left:15%">
                                        <div class="col-md-4">
                                            Total Hours:
                                        </div>
                                        <div class="col-md-3" style="text-align:left;">
                                            <span id="totalhrs" style="font-size:100%;" class="myclass">@ViewBag.Totalhours</span>
                                        </div>
                                    </div>
                                    <div class="col col-md-5 pull-left total" style="font-size:18px;padding-left:5%">
                                        <div class="col-md-5">
                                            Till date avg:
                                        </div>
                                        <div>
                                            @ViewBag.tilldateaverage
                                        </div>

                                    </div>

                                </div>*@
                        </div>
                        <div class="panel-footer" style="height:15%;background-color:#0C2658;text-align:right;">
                            <button type="button" class="btn btn-outline-info " style="background-color:#748CAB;color: white;" onclick="showTableData()">Save</button>
                            <button type="button" class="btn btn-outline-info " style="background-color:#748CAB;color: white;">Cancel</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }
</body>